[package]
name = "rust-expression"
version = "0.1.1"
authors = ["Martin Suesskraut <martin.suesskraut@gmail.com>"]
license = "MIT"
edition = "2018"

description = "Calculator and solver for linear equations."
repository = "https://github.com/msuesskraut/calc"
readme = "Readme.md"
keywords = ["calc", "math", "solver"]
categories = ["mathematics"]

[dependencies]

pest = "2.1.3"
pest_derive = "2.1.0"
lazy_static = "1.4.0"

[dev-dependencies]

linefeed = "0.6.0"
